### ISSUE TITLE
Scaling issue?

### ISSUE THREAD

**Issue by FredTungsten** [FredTungsten/ScriptPlayer#128]
http://realtouchscripts.com/viewtopic.php?f=59&t=9453&start=10#p25866

Might be related to Windows DPI scaling on 4k

**Comment by FredTungsten** [comment]
Still no closer to a solution ... seems to be related to DPI-Scaling, the monitor it was launched on and the monitor it goes fullscreen. Might take a while.

**Comment by mument** [comment]
I'm experiencing this and it does seem to be DPI scaling causing it. Anything beyond 100% scaling seems to be causing a problem.

**Comment by FredTungsten** [comment]
Well, I hope I'll ever find the time to solve this - as things currently are it might take a while

**Comment by mument** [comment]
I have a way to fix it. Go to Scriptplayer.exe Properties>Compatibility>Change High DPI Settings. At the bottom of the window there is a setting 'High DPI Scaling Override' - click that and I selected 'System (enhanced)'. When you OK that just remember to unclick 'Run this program as an Administrator' otherwise you'll get a SmartScreen window asking for permission to run it everytime you open it.

**Comment by FredTungsten** [comment]
I think I found a way to fix it, ironically by disabling DPI-awareness for the app. 
Seems to have interfered with this stupid system setting (works fine when disabled, but this is a global setting):

![image](https://user-images.githubusercontent.com/28461114/77222926-288f5e80-6b58-11ea-8042-8347a1e1560d.png)

SP might become a bit blurry now, but that's probably better than telling people to change their system settings because of a single program.

**Comment by mument** [comment]
Is that available to have now? My fix threw up a different problem with drop down menus at the top not working as they should.

**Comment by FredTungsten** [comment]
https://github.com/FredTungsten/ScriptPlayer/wiki/Downloading-Beta-Builds
