### ISSUE TITLE
OSR/OSR2 compatibility

### ISSUE THREAD

**Issue by MarkusWo** [FredTungsten/ScriptPlayer#163]
I know you said that you don't handle new gear requests, but who would I ask about adding [OSR/OSR2](https://www.patreon.com/tempestvr) support for ScriptPlayer? OSR seems to be becoming pretty popular and Raser1 JoyFunPlayer already supports it.

**Comment by FredTungsten** [comment]
I think qDot was trying to integrate that into Buttplug/Intiface - which is where it actually belongs. I only integrated The Handy because it doesn't fit the command-based approach of any other device.

I also accept clean Pull Requests, so if someone wants to send me one I see no reason to decline (not very likely though, Raser seems to code closed-source exclusively)

**Comment by qdot** [comment]
Yeah, OSR2 support is still coming Any Day Now, just trying to finish this stupid library consolidate to buttplug-rs first and it keeps taking longer than planned.
