### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by SleepyPrince** [FredTungsten/ScriptPlayer#207]
Is there any build instructions available? I keep running into namespace issues trying to build it.

**Comment by FredTungsten** [comment]
None whatsoever, sorry.
Since it works in [AppVeyor](https://github.com/FredTungsten/ScriptPlayer/blob/master/appveyor.yml), the build settings work even on a completely blank system.

This *should* work (on Windows 10):

- Open the solution in VS 2017
- Make sure you select the "Debug" configuration
- Click "Re-Build All" to make sure you have all the nuget packages needed

**Comment by SleepyPrince** [comment]
I think I got it working now, the Windows namespace is pointing to a different file probably because of different Windows SDK version.

**Comment by backtrip** [comment]
I have the exact same issue with the "Windows" namespace not available, can you tell me how you were able to fix it? Did you install another SDK or manually redirect something?

**Comment by SleepyPrince** [comment]
I think I changed the version number in this.
https://github.com/FredTungsten/ScriptPlayer/blob/47eadff3b625f5d1529bbcceedbb5aa654680c08/ScriptPlayer/ScriptPlayer.Shared/ScriptPlayer.Shared.csproj#L117
You might want to look for similar line in other .csproj files.
