### ISSUE TITLE
Request: Stay on top

### ISSUE THREAD

**Issue by i3jjnc68emm** [FredTungsten/ScriptPlayer#43]
Would be nice to have a stay on top function, should be very easy to add

**Comment by FredTungsten** [comment]
>should be very easy to add
Indeed. Out of curiosity: Why do you need it?

**Comment by i3jjnc68emm** [comment]
I have two players opened. This script player so I can change the current playing video if I like to and another video player in background, full windowed. As of now if I click on something i nthe background player the script player disappears to background. I also don't want to make them side-by-side as the script player then takes too much space.

So just having it staying opened at my screen corner is very useful if you do something in background.

**Comment by FredTungsten** [comment]
Ok, since you are the fist person to request that, you get the bonus of having a say in the details :smile:

Right now I would simply add that as an option to the settings-dialog (checkbox on/off). Would that work for you or is this something you might want to enable/disable quickly like the settings in the hidden sidebar? Separate option for the playlist?

**Comment by i3jjnc68emm** [comment]
We have a nice toolbar with only a few items in there. How about "View -> Stay on top" checkbox? I believe if at alll, this is an option you toggle in purpose so having it "hardcoded" into settings is the wrong place I believe.

**Comment by FredTungsten** [comment]
Should be done compiling in a minute or so:
https://ci.appveyor.com/project/FredTungsten/scriptplayer/build/job/sj83g2epdd0vy2rg/artifacts
