### ISSUE TITLE
Script debugger

### ISSUE THREAD

**Issue by asphalter** [FredTungsten/ScriptPlayer#76]
Most of us like to script using Blender with plugin or other funscript editors, but we obviously like to debug the script on the field, using ScriptPlayer.

Could you please implement on the "Script Position" debug overlay, an indication of which positions are skipped (because near to the next command) or overriden with something different by the player, considering the user settings (Range, Speed, Speed Multiplier, Playback rate,...)?
Maybe you could simply use a dot with different colour on the position graph, and you could also allow to see a summary to know the number of skipped and overriden positions in the whole script.

I think this could help all the script makers out there. Do you agree?

Thanks

**Comment by FredTungsten** [comment]
Hmm .... well, which commands get skipped isn't that easy to say since it depends mainly on the "Min Command Delay" setting, the used device and what kind of commands follow. Scriptplayer doen't just skip commands, but tries to remove duplicate ones that the user won't miss if the same ones come up over and over again. I could however color the dots depending on whether the delay is shorter than the Min Command Delay or some other factors ... I'll give this one some thought next weekend.

**Comment by FredTungsten** [comment]
It's true though - since I never made [my script editor](https://github.com/FredTungsten/ScriptPlayer/tree/master/ScriptPlayer/ScriptPlayer.VideoSync) user friendly enough for a release version, at least the player could use some basic debugging and editing functions.

**Comment by FredTungsten** [comment]
I've added some color to the position bar (latest beta):

The dots color indicates the time to the previous command. Anything longer than the Min. Command Delay is green, anything shorter is red - when it gets close to the minimum it's yellow.

The line color indicates the predicted speed (red = 100%) with a similar color-scheme as the heatmap.

**Comment by FredTungsten** [comment]
Oh, and I've added a "Reload Script" button to the debug section so you can quickly reload the script after making changes in the editor.
