### ISSUE TITLE
Cannot connect to Buttplug - Missing Dependancy

### ISSUE THREAD

**Issue by dastardlii** [FredTungsten/ScriptPlayer#97]
Using the latest beta (ScriptPlayer-Debug-1.0.5.183), Trying to connect to a buttplug server will always fail.  From the connection logs there is the following error:

================= 3/18/2019 9:30:15 PM  =================
Could not load file or assembly 'SuperSocket.ClientEngine, Version=0.10.0.0, Culture=neutral, PublicKeyToken=ee9af13f57f00acc' or one of its dependencies. The system cannot find the file specified.
   at Buttplug.Client.ButtplugWSClient.<Connect>d__37.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Buttplug.Client.ButtplugWSClient.Connect(Uri aURL, Boolean aIgnoreSSLErrors)
   at ScriptPlayer.Shared.ButtplugAdapter.<Connect>d__6.MoveNext()

**Comment by dastardlii** [comment]
Note that putting the SuperSocket.ClientEngine dll (.net 4.0) in the scriptplayer directory fixes the issue, but that file is not included with the installer.

**Comment by FredTungsten** [comment]
Thanks for pointing that out. Apparently the last released version (0.2.3) of the buttplug client had an old reference to SuperSocket 8 (instead of 10). qDot is currently working on a new Version of the client library which doesn't have a UI yet so I manually updated the reference until the new version is released.
Latest build should work out of the box.
